name: Gh-Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GH-Pages
        uses: bluefireteam/flutter-gh-pages@v8
        with:
          workingDir: build/web
          targetBranch: gh-pages