name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - run: flutter build web --release --base-href /AlienAttack/ --pwa-strategy=none
      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /AlienAttack/